### ISSUE TITLE
New agent fty-metric-snmp

### ISSUE THREAD

**Issue by thalman** [42ity/FTY#1]
Agent for creating metrics using SNMP and generally with anything possible in lua or script

https://github.com/thalman/fty-metric-snmp

This way we can monitor (not only) SNMP enabled servers, disk-arrays. Not only power devices.

**Comment by vyskocilm** [comment]
(y)

**Comment by vyskocilm** [comment]
Created https://github.com/42ity/fty-metric-snmp

Please push your code there

**Comment by jimklimov** [comment]
Submodule link in FTY dispatcher added (and then changed to the 42ity replica); Makefile recipes introduced but not enabled by default.

**Comment by jimklimov** [comment]
Done over a month ago, tracked as an experimental component in the Makefile for now.
