### ISSUE TITLE
New agent fty-alert-flexible

### ISSUE THREAD

**Issue by thalman** [42ity/FTY#2]
Agent for creating alerts in much more flexible way. Supports groups, device models and particular asset matching.

Supports integration with nagios metrics.

https://github.com/thalman/fty-alert-flexible

**Comment by vyskocilm** [comment]
It's interesting to see the nagios integration part. I know this was one of the most wanted features, which was skipped during MVP.

**Comment by vyskocilm** [comment]
Created https://github.com/42ity/fty-alert-flexible

Please push your code there

**Comment by jimklimov** [comment]
Submodule link in FTY dispatcher added (and then changed to the 42ity replica); Makefile recipes introduced but not enabled by default.

**Comment by jimklimov** [comment]
Done over a month ago, tracked as an experimental component in the Makefile for now.

**Comment by jimklimov** [comment]
Moved to common components - used in new generation of production OS images.
