### ISSUE TITLE
New agent fty-fty-mdns-sd

### ISSUE THREAD

**Issue by geraldguillaume** [42ity/FTY#3]
This new agent manages network announcement(mDNS) and discovery (DNS-SD).
It collects information from fty-info agent, then it publishes it to avahi-deamon (mDNS).
For now, discovery is not yet implemented

https://github.com/geraldguillaume/fty-mdns-sd

**Comment by jimklimov** [comment]
It would be preferable to track a repo straight from 42ity - when Tom's projects were added and then relocated, some already checked out workspaces and forked collaborators got upset ;)
Do you have access to move this repo and then make a fork in your own account?

**Comment by aquette** [comment]
I get the point of people forking the repo of the new agent from the author's personal part, prior to having it integrating it in 42ITy.
We have to complete the procedure in https://github.com/42ity/fty-example
I have a few additions in mind that I'll propose as a PR to fty-example...

**Comment by jimklimov** [comment]
Done, tracked as an experimental component in the Makefile for now.
