### ISSUE TITLE
fty-prometheus-rest new REST_API library

### ISSUE THREAD

**Issue by geraldguillaume** [42ity/FTY#5]
fty-prometheus-rest is a prometheus collector.

Promotheus is a scalable metrics collector developed in go technology, combined with Grafana web UI  interface , it allows to create custom dashboard connected  with multiple FTY devices.
This library exposes internal metrics (realpower, temperature, humidity) in prometheus format https://_fty-device-ip_>/metrics.

https://github.com/geraldguillaume/fty-prometheus-rest

**Comment by jimklimov** [comment]
A new FTY upstream was cloned from @geraldguillaume repo, as https://github.com/42ity/fty-prometheus-rest

Integration with dispatcher TBD

**Comment by jimklimov** [comment]
Now tracked as part of the FTY dispatcher repo, added to its `Makefile` with initial assumptions about dependencies (as an experimental bit).
